version: "3.9"

services:
  postgres-db1:
    image: postgres:16
    container_name: postgres-db1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: db-1
      POSTGRES_USER: postgres1
      POSTGRES_PASSWORD: pass1
      TZ: Europe/Kyiv
    volumes:
      - ./docker/db/init_db1.sql:/docker-entrypoint-initdb.d/init.sql

  postgres-db2:
    image: postgres:16
    container_name: postgres-db2
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: db-2
      POSTGRES_USER: postgres2
      POSTGRES_PASSWORD: pass2
      TZ: Europe/Kyiv
    volumes:
      - ./docker/db/init_db2.sql:/docker-entrypoint-initdb.d/init.sql

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: db-3
      MYSQL_USER: mysql
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/db/init_db3.sql:/docker-entrypoint-initdb.d/init.sql